In [3]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_linnerud
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
data = load_linnerud()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.DataFrame(data.target, columns=data.target_names)

X.head(), y.head()

(   Chins  Situps  Jumps
 0    5.0   162.0   60.0
 1    2.0   110.0   60.0
 2   12.0   101.0  101.0
 3   12.0   105.0   37.0
 4   13.0   155.0   58.0,
    Weight  Waist  Pulse
 0   191.0   36.0   50.0
 1   189.0   37.0   52.0
 2   193.0   38.0   58.0
 3   162.0   35.0   62.0
 4   189.0   35.0   46.0)

In [5]:
X.describe()

           Chins      Situps      Jumps
count  20.000000   20.000000   20.00000
mean    9.450000  145.550000   70.30000
std     5.286278   62.566575   51.27747
min     1.000000   50.000000   25.00000
25%     4.750000  101.000000   39.50000
50%    11.500000  122.500000   54.00000
75%    13.250000  210.000000   85.25000
max    17.000000  251.000000  250.00000

In [6]:
y.describe()

           Weight      Waist      Pulse
count   20.000000  20.000000  20.000000
mean   178.600000  35.400000  56.100000
std     24.690505   3.201973   7.210373
min    138.000000  31.000000  46.000000
25%    160.750000  33.000000  51.500000
50%    176.000000  35.000000  55.000000
75%    191.500000  37.000000  60.500000
max    247.000000  46.000000  74.000000

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)

In [11]:
mse = mean_squared_error(y_test, y_pred, multioutput='raw_values')
print("MSE for Weight, Waist, Pulse:", mse)

MSE for Weight, Waist, Pulse: [630.77570979   4.57089582  82.11441002]

Weight values are large numbers, Squaring the error makes this number look big.Exercise performance alone is not sufficient to accurately predict body weight.
Waist values are of very small error, model predicts waist size reasonably well.Thus Fitness activity has a strong relationship with waist size.
Pulse value shows Moderate error, pulse rate is influenced by many factors (stress, genetics, health). Thus Exercise variables only partially explain pulse rate.

In [12]:
r2 = r2_score(y_test, y_pred, multioutput='raw_values')
print("R² Score for Weight, Waist, Pulse:", r2)

R² Score for Weight, Waist, Pulse: [-1.24325658 -0.0755049  -2.73247318]

The model performs best in predicting waist circumference, indicating a strong relationship between physical fitness performance and abdominal measurements. Prediction accuracy for body weight and pulse rate is comparatively weaker, suggesting that these physiological characteristics depend on additional factors beyond exercise capacity alone. Overall, the results demonstrate that machine learning can capture meaningful relationships, but predictive performance varies across different health indicators.